name: meetplace

description: MeetPlace

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  firebase_core: ^3.15.1
  firebase_auth: ^5.6.2
  cloud_firestore: ^5.6.11
  firebase_storage: ^12.4.9
  firebase_messaging: ^15.2.9
  shared_preferences: ^2.5.3
  intl: ^0.20.2
  uuid: ^4.5.1
  cupertino_icons: ^1.0.6
  image_picker: ^1.0.4
  url_launcher: ^6.1.14
  google_fonts: ^6.2.1
  google_sign_in: ^6.1.6
  sign_in_with_apple: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true